#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

main() {
  local -r base_image="$(DOCKER_BUILDKIT=1 docker build \
    --build-arg black=20.8b1 \
    --build-arg git=2.26.2 \
    --build-arg gitlint=0.13.1 \
    --build-arg hadolint=1.18.0 \
    --build-arg htmlhint=0.14.1 \
    --build-arg prettier_toml=0.3.1 \
    --build-arg prettier_xml=0.12.0 \
    --build-arg prettier=2.1.2 \
    --build-arg pylint=2.6.0 \
    --build-arg shellcheck=0.7.1 \
    --build-arg stylelint=13.7.2 \
    --build-arg vnu=20.6.30 \
    --quiet \
    https://github.com/evolutics/code-cleaner-buffet.git#0.14.0)"

  docker build \
    --build-arg base_image="${base_image}" \
    --file "${DOCKERFILE_PATH}" \
    --tag "${IMAGE_NAME}" \
    .
}

main "$@"
